import type { Project } from "@/components/asset-templates-table"

/** Company-level project directory (used in asset register and template assignment). */
export const COMPANY_PROJECTS: Project[] = [
  { id: "res-1", name: "Sunset Hills Condominiums" },
  { id: "res-2", name: "Maple Grove Apartments" },
  { id: "res-3", name: "Riverside Townhomes" },
  { id: "res-4", name: "Harbor View Residences" },
  { id: "res-5", name: "Oak Park Senior Living" },
  { id: "com-1", name: "Downtown Office Plaza" },
  { id: "com-2", name: "Westgate Shopping Center" },
  { id: "com-3", name: "Metro Business Park" },
  { id: "com-4", name: "Central Station Retail" },
  { id: "com-5", name: "Lakeside Corporate Campus" },
  { id: "hc-1", name: "St. Mary's Medical Center" },
  { id: "hc-2", name: "Northside Community Hospital" },
  { id: "hc-3", name: "Valley Health Clinic" },
  { id: "hc-4", name: "Children's Specialty Center" },
  { id: "ind-1", name: "Eastside Manufacturing Plant" },
  { id: "ind-2", name: "Harbor Logistics Center" },
  { id: "ind-3", name: "Tech Park Data Center" },
  { id: "ind-4", name: "Regional Distribution Hub" },
  { id: "dc-1", name: "CloudFirst Data Center" },
  { id: "dc-2", name: "SecureVault Colocation" },
  { id: "dc-3", name: "Enterprise Compute Facility" },
  { id: "wf-1", name: "North Sea Offshore Wind Phase II" },
  { id: "wf-2", name: "Great Plains Wind Energy Hub" },
  { id: "wf-3", name: "Coastal Ridge Repower Project" },
  { id: "hw-1", name: "I-95 North Corridor Reconstruction" },
  { id: "hw-2", name: "Mountain Pass Expressway Phase 3" },
  { id: "hw-3", name: "Urban Beltway ITS & Safety Upgrade" },
  { id: "ap-1", name: "Midcontinent International Terminal Expansion" },
  { id: "ap-2", name: "Pacific Hub Cargo & Apron Modernization" },
  { id: "ap-3", name: "Regional Airport Runway 09L/27R Rehabilitation" },
]
