import type { AssetType } from "@/app/page"

/** Asset type trees per template (matches Asset Settings / template detail). */
export const TEMPLATE_ASSET_TYPES = {
  "template-default": [],
  "template-residential": [
    { id: "res-01", name: "Site & Grounds", code: "01", fieldset: "01_Fieldset", hasSubtypes: true },
    { id: "res-01-lnd", name: "Landscaping", code: "01-LND", fieldset: "01_Fieldset", parentId: "res-01", hasSubtypes: true },
    { id: "res-01-lnd-irr", name: "Irrigation Systems", code: "01-LND-IRR", fieldset: "01_Fieldset", parentId: "res-01-lnd" },
    { id: "res-01-lnd-lgt", name: "Landscape Lighting", code: "01-LND-LGT", fieldset: "01_Fieldset", parentId: "res-01-lnd" },
    { id: "res-22", name: "Plumbing Systems", code: "22", fieldset: "22_Fieldset", hasSubtypes: true },
    { id: "res-22-dom", name: "Domestic Water", code: "22-DOM", fieldset: "22-DOM_Fieldset", parentId: "res-22", hasSubtypes: true },
    { id: "res-22-dom-hwh", name: "Water Heaters", code: "22-DOM-HWH", fieldset: "22-DOM_Fieldset", parentId: "res-22-dom" },
    { id: "res-22-dom-pmp", name: "Booster Pumps", code: "22-DOM-PMP", fieldset: "22-DOM_Fieldset", parentId: "res-22-dom" },
    { id: "res-23", name: "HVAC Systems", code: "23", fieldset: "23_Fieldset", hasSubtypes: true },
    { id: "res-23-hva", name: "Heating & Cooling", code: "23-HVA", fieldset: "23-HVA_Fieldset", parentId: "res-23", hasSubtypes: true },
    { id: "res-23-hva-rtu", name: "Rooftop Units", code: "23-HVA-RTU", fieldset: "23-HVA_Fieldset", parentId: "res-23-hva" },
    { id: "res-23-hva-spl", name: "Split Systems", code: "23-HVA-SPL", fieldset: "23-HVA_Fieldset", parentId: "res-23-hva" },
    { id: "res-26", name: "Electrical Systems", code: "26", fieldset: "26_Fieldset", hasSubtypes: true },
    { id: "res-26-pwr", name: "Power Distribution", code: "26-PWR", fieldset: "26-PWR_Fieldset", parentId: "res-26", hasSubtypes: true },
    { id: "res-26-pwr-swg", name: "Switchgear", code: "26-PWR-SWG", fieldset: "26-PWR_Fieldset", parentId: "res-26-pwr" },
    { id: "res-26-pwr-pnl", name: "Panel Boards", code: "26-PWR-PNL", fieldset: "26-PWR_Fieldset", parentId: "res-26-pwr" },
    { id: "res-28", name: "Life Safety", code: "28", fieldset: "28_Fieldset", hasSubtypes: true },
    { id: "res-28-fir", name: "Fire Protection", code: "28-FIR", fieldset: "28-FIR_Fieldset", parentId: "res-28", hasSubtypes: true },
    { id: "res-28-fir-spr", name: "Sprinkler Systems", code: "28-FIR-SPR", fieldset: "28-FIR_Fieldset", parentId: "res-28-fir" },
    { id: "res-28-fir-alm", name: "Fire Alarms", code: "28-FIR-ALM", fieldset: "28-FIR_Fieldset", parentId: "res-28-fir" },
  ],
  "template-commercial": [
    { id: "com-01", name: "Site Infrastructure", code: "01", fieldset: "01_Fieldset", hasSubtypes: true },
    { id: "com-01-prk", name: "Parking Systems", code: "01-PRK", fieldset: "01-PRK_Fieldset", parentId: "com-01", hasSubtypes: true },
    { id: "com-01-prk-gat", name: "Parking Gates", code: "01-PRK-GAT", fieldset: "01-PRK_Fieldset", parentId: "com-01-prk" },
    { id: "com-01-prk-pay", name: "Payment Systems", code: "01-PRK-PAY", fieldset: "01-PRK_Fieldset", parentId: "com-01-prk" },
    { id: "com-14", name: "Vertical Transportation", code: "14", fieldset: "14_Fieldset", hasSubtypes: true },
    { id: "com-14-elv", name: "Elevators", code: "14-ELV", fieldset: "14-ELV_Fieldset", parentId: "com-14", hasSubtypes: true },
    { id: "com-14-elv-psg", name: "Passenger Elevators", code: "14-ELV-PSG", fieldset: "14-ELV_Fieldset", parentId: "com-14-elv" },
    { id: "com-14-elv-frt", name: "Freight Elevators", code: "14-ELV-FRT", fieldset: "14-ELV_Fieldset", parentId: "com-14-elv" },
    { id: "com-21", name: "Fire Suppression", code: "21", fieldset: "21_Fieldset", hasSubtypes: true },
    { id: "com-21-spr", name: "Sprinkler Systems", code: "21-SPR", fieldset: "21-SPR_Fieldset", parentId: "com-21", hasSubtypes: true },
    { id: "com-21-spr-wet", name: "Wet Pipe Systems", code: "21-SPR-WET", fieldset: "21-SPR_Fieldset", parentId: "com-21-spr" },
    { id: "com-21-spr-dry", name: "Dry Pipe Systems", code: "21-SPR-DRY", fieldset: "21-SPR_Fieldset", parentId: "com-21-spr" },
    { id: "com-23", name: "HVAC Systems", code: "23", fieldset: "23_Fieldset", hasSubtypes: true },
    { id: "com-23-chl", name: "Central Plant", code: "23-CHL", fieldset: "23-CHL_Fieldset", parentId: "com-23", hasSubtypes: true },
    { id: "com-23-chl-chr", name: "Chillers", code: "23-CHL-CHR", fieldset: "23-CHL_Fieldset", parentId: "com-23-chl" },
    { id: "com-23-chl-blr", name: "Boilers", code: "23-CHL-BLR", fieldset: "23-CHL_Fieldset", parentId: "com-23-chl" },
    { id: "com-26", name: "Electrical", code: "26", fieldset: "26_Fieldset", hasSubtypes: true },
    { id: "com-26-gen", name: "Emergency Power", code: "26-GEN", fieldset: "26-GEN_Fieldset", parentId: "com-26", hasSubtypes: true },
    { id: "com-26-gen-dsl", name: "Diesel Generators", code: "26-GEN-DSL", fieldset: "26-GEN_Fieldset", parentId: "com-26-gen" },
    { id: "com-26-gen-ups", name: "UPS Systems", code: "26-GEN-UPS", fieldset: "26-GEN_Fieldset", parentId: "com-26-gen" },
  ],
  "template-healthcare": [
    { id: "hc-11", name: "Medical Equipment", code: "11", fieldset: "11_Fieldset", hasSubtypes: true },
    { id: "hc-11-img", name: "Imaging Equipment", code: "11-IMG", fieldset: "11-IMG_Fieldset", parentId: "hc-11", hasSubtypes: true },
    { id: "hc-11-img-mri", name: "MRI Systems", code: "11-IMG-MRI", fieldset: "11-IMG_Fieldset", parentId: "hc-11-img" },
    { id: "hc-11-img-xry", name: "X-Ray Systems", code: "11-IMG-XRY", fieldset: "11-IMG_Fieldset", parentId: "hc-11-img" },
    { id: "hc-11-img-ctn", name: "CT Scanners", code: "11-IMG-CTN", fieldset: "11-IMG_Fieldset", parentId: "hc-11-img" },
    { id: "hc-22", name: "Medical Gases", code: "22", fieldset: "22_Fieldset", hasSubtypes: true },
    { id: "hc-22-gas", name: "Gas Systems", code: "22-GAS", fieldset: "22-GAS_Fieldset", parentId: "hc-22", hasSubtypes: true },
    { id: "hc-22-gas-oxy", name: "Oxygen Systems", code: "22-GAS-OXY", fieldset: "22-GAS_Fieldset", parentId: "hc-22-gas" },
    { id: "hc-22-gas-vac", name: "Vacuum Systems", code: "22-GAS-VAC", fieldset: "22-GAS_Fieldset", parentId: "hc-22-gas" },
    { id: "hc-23", name: "HVAC Systems", code: "23", fieldset: "23_Fieldset", hasSubtypes: true },
    { id: "hc-23-ahu", name: "Air Handling", code: "23-AHU", fieldset: "23-AHU_Fieldset", parentId: "hc-23", hasSubtypes: true },
    { id: "hc-23-ahu-ort", name: "Operating Room AHUs", code: "23-AHU-ORT", fieldset: "23-AHU_Fieldset", parentId: "hc-23-ahu" },
    { id: "hc-23-ahu-iso", name: "Isolation Room AHUs", code: "23-AHU-ISO", fieldset: "23-AHU_Fieldset", parentId: "hc-23-ahu" },
    { id: "hc-26", name: "Electrical Systems", code: "26", fieldset: "26_Fieldset", hasSubtypes: true },
    { id: "hc-26-crt", name: "Critical Power", code: "26-CRT", fieldset: "26-CRT_Fieldset", parentId: "hc-26", hasSubtypes: true },
    { id: "hc-26-crt-gen", name: "Emergency Generators", code: "26-CRT-GEN", fieldset: "26-CRT_Fieldset", parentId: "hc-26-crt" },
    { id: "hc-26-crt-ups", name: "UPS Systems", code: "26-CRT-UPS", fieldset: "26-CRT_Fieldset", parentId: "hc-26-crt" },
    { id: "hc-28", name: "Life Safety", code: "28", fieldset: "28_Fieldset", hasSubtypes: true },
    { id: "hc-28-nrs", name: "Nurse Call", code: "28-NRS", fieldset: "28-NRS_Fieldset", parentId: "hc-28", hasSubtypes: true },
    { id: "hc-28-nrs-std", name: "Nurse Call Stations", code: "28-NRS-STD", fieldset: "28-NRS_Fieldset", parentId: "hc-28-nrs" },
    { id: "hc-28-nrs-cod", name: "Code Blue", code: "28-NRS-COD", fieldset: "28-NRS_Fieldset", parentId: "hc-28-nrs" },
  ],
  "template-industrial": [
    { id: "ind-11", name: "Process Equipment", code: "11", fieldset: "11_Fieldset", hasSubtypes: true },
    { id: "ind-11-prd", name: "Production Equipment", code: "11-PRD", fieldset: "11-PRD_Fieldset", parentId: "ind-11", hasSubtypes: true },
    { id: "ind-11-prd-cnc", name: "CNC Machines", code: "11-PRD-CNC", fieldset: "11-PRD_Fieldset", parentId: "ind-11-prd" },
    { id: "ind-11-prd-cnv", name: "Conveyors", code: "11-PRD-CNV", fieldset: "11-PRD_Fieldset", parentId: "ind-11-prd" },
    { id: "ind-11-prd-crn", name: "Cranes", code: "11-PRD-CRN", fieldset: "11-PRD_Fieldset", parentId: "ind-11-prd" },
    { id: "ind-22", name: "Industrial Plumbing", code: "22", fieldset: "22_Fieldset", hasSubtypes: true },
    { id: "ind-22-prc", name: "Process Water", code: "22-PRC", fieldset: "22-PRC_Fieldset", parentId: "ind-22", hasSubtypes: true },
    { id: "ind-22-prc-di", name: "DI Water", code: "22-PRC-DI", fieldset: "22-PRC_Fieldset", parentId: "ind-22-prc" },
    { id: "ind-22-prc-chl", name: "Chilled Water", code: "22-PRC-CHL", fieldset: "22-PRC_Fieldset", parentId: "ind-22-prc" },
    { id: "ind-23", name: "Industrial HVAC", code: "23", fieldset: "23_Fieldset", hasSubtypes: true },
    { id: "ind-23-vnt", name: "Ventilation", code: "23-VNT", fieldset: "23-VNT_Fieldset", parentId: "ind-23", hasSubtypes: true },
    { id: "ind-23-vnt-exh", name: "Exhaust Systems", code: "23-VNT-EXH", fieldset: "23-VNT_Fieldset", parentId: "ind-23-vnt" },
    { id: "ind-23-vnt-mau", name: "Makeup Air", code: "23-VNT-MAU", fieldset: "23-VNT_Fieldset", parentId: "ind-23-vnt" },
    { id: "ind-26", name: "Industrial Electrical", code: "26", fieldset: "26_Fieldset", hasSubtypes: true },
    { id: "ind-26-mcc", name: "Motor Control", code: "26-MCC", fieldset: "26-MCC_Fieldset", parentId: "ind-26", hasSubtypes: true },
    { id: "ind-26-mcc-str", name: "Starters", code: "26-MCC-STR", fieldset: "26-MCC_Fieldset", parentId: "ind-26-mcc" },
    { id: "ind-26-mcc-vfd", name: "VFDs", code: "26-MCC-VFD", fieldset: "26-MCC_Fieldset", parentId: "ind-26-mcc" },
    { id: "ind-40", name: "Process Integration", code: "40", fieldset: "40_Fieldset", hasSubtypes: true },
    { id: "ind-40-plc", name: "Control Systems", code: "40-PLC", fieldset: "40-PLC_Fieldset", parentId: "ind-40", hasSubtypes: true },
    { id: "ind-40-plc-dcs", name: "DCS", code: "40-PLC-DCS", fieldset: "40-PLC_Fieldset", parentId: "ind-40-plc" },
    { id: "ind-40-plc-hmi", name: "HMI", code: "40-PLC-HMI", fieldset: "40-PLC_Fieldset", parentId: "ind-40-plc" },
  ],
  "template-datacenter": [
    { id: "dc-23", name: "Mechanical & HVAC", code: "23", fieldset: "23_Fieldset", hasSubtypes: true },
    { id: "dc-23-gen", name: "Cooling Generation", code: "23-GEN", fieldset: "23-GEN_Fieldset", parentId: "dc-23", hasSubtypes: true },
    { id: "dc-23-gen-chl", name: "Chiller Units", code: "23-GEN-CHL", fieldset: "23-GEN_Fieldset", parentId: "dc-23-gen" },
    { id: "dc-23-gen-ctw", name: "Cooling Towers", code: "23-GEN-CTW", fieldset: "23-GEN_Fieldset", parentId: "dc-23-gen" },
    { id: "dc-23-gen-hex", name: "Heat Exchangers", code: "23-GEN-HEX", fieldset: "23-GEN_Fieldset", parentId: "dc-23-gen" },
    { id: "dc-23-air", name: "Air Handling & Room Cooling", code: "23-AIR", fieldset: "23-AIR_Fieldset", parentId: "dc-23", hasSubtypes: true },
    { id: "dc-23-air-crc", name: "CRAC Units", code: "23-AIR-CRC", fieldset: "23-AIR_Fieldset", parentId: "dc-23-air" },
    { id: "dc-23-air-crh", name: "CRAH Units", code: "23-AIR-CRH", fieldset: "23-AIR_Fieldset", parentId: "dc-23-air" },
    { id: "dc-23-air-irc", name: "In-Row Cooling", code: "23-AIR-IRC", fieldset: "23-AIR_Fieldset", parentId: "dc-23-air" },
    { id: "dc-23-pmp", name: "Fluid Distribution", code: "23-PMP", fieldset: "23-PMP_Fieldset", parentId: "dc-23", hasSubtypes: true },
    { id: "dc-23-pmp-cwp", name: "Chilled Water Pumps", code: "23-PMP-CWP", fieldset: "23-PMP_Fieldset", parentId: "dc-23-pmp" },
    { id: "dc-23-pmp-vlv", name: "Control Valves", code: "23-PMP-VLV", fieldset: "23-PMP_Fieldset", parentId: "dc-23-pmp" },
    { id: "dc-26", name: "Electrical Systems", code: "26", fieldset: "26_Fieldset", hasSubtypes: true },
    { id: "dc-26-pwr", name: "Power Distribution", code: "26-PWR", fieldset: "26-PWR_Fieldset", parentId: "dc-26", hasSubtypes: true },
    { id: "dc-26-pwr-pdu", name: "PDUs", code: "26-PWR-PDU", fieldset: "26-PWR_Fieldset", parentId: "dc-26-pwr" },
    { id: "dc-26-pwr-sts", name: "Static Transfer Switches", code: "26-PWR-STS", fieldset: "26-PWR_Fieldset", parentId: "dc-26-pwr" },
    { id: "dc-26-ups", name: "UPS Systems", code: "26-UPS", fieldset: "26-UPS_Fieldset", parentId: "dc-26", hasSubtypes: true },
    { id: "dc-26-ups-mod", name: "Modular UPS", code: "26-UPS-MOD", fieldset: "26-UPS_Fieldset", parentId: "dc-26-ups" },
    { id: "dc-26-ups-bat", name: "Battery Systems", code: "26-UPS-BAT", fieldset: "26-UPS_Fieldset", parentId: "dc-26-ups" },
    { id: "dc-26-gen", name: "Emergency Power", code: "26-GEN", fieldset: "26-GEN_Fieldset", parentId: "dc-26", hasSubtypes: true },
    { id: "dc-26-gen-dsl", name: "Diesel Generators", code: "26-GEN-DSL", fieldset: "26-GEN_Fieldset", parentId: "dc-26-gen" },
    { id: "dc-26-gen-ats", name: "ATS", code: "26-GEN-ATS", fieldset: "26-GEN_Fieldset", parentId: "dc-26-gen" },
  ],
  "template-windfarm": [
    { id: "wf-01", name: "Wind Turbine Systems", code: "WF-01", fieldset: "WF_TURB_Fieldset", isAssembly: true, hasSubtypes: true },
    { id: "wf-01-nac", name: "Nacelle & Drivetrain", code: "WF-01-NAC", fieldset: "WF_NAC_Fieldset", parentId: "wf-01", hasSubtypes: true },
    { id: "wf-01-nac-gen", name: "Main Generator", code: "WF-01-NAC-GEN", fieldset: "WF_NAC_Fieldset", parentId: "wf-01-nac" },
    { id: "wf-01-nac-gbx", name: "Gearbox", code: "WF-01-NAC-GBX", fieldset: "WF_NAC_Fieldset", parentId: "wf-01-nac" },
    { id: "wf-01-rot", name: "Rotor & Blades", code: "WF-01-ROT", fieldset: "WF_ROT_Fieldset", parentId: "wf-01", hasSubtypes: true },
    { id: "wf-01-rot-bld", name: "Blade Sets", code: "WF-01-ROT-BLD", fieldset: "WF_ROT_Fieldset", parentId: "wf-01-rot" },
    { id: "wf-01-rot-hub", name: "Hub & Pitch", code: "WF-01-ROT-HUB", fieldset: "WF_ROT_Fieldset", parentId: "wf-01-rot" },
    { id: "wf-01-twr", name: "Tower & Foundation", code: "WF-01-TWR", fieldset: "WF_TWR_Fieldset", parentId: "wf-01", hasSubtypes: true },
    { id: "wf-01-twr-st", name: "Tower Structure", code: "WF-01-TWR-ST", fieldset: "WF_TWR_Fieldset", parentId: "wf-01-twr" },
    { id: "wf-01-twr-fnd", name: "Foundation", code: "WF-01-TWR-FND", fieldset: "WF_TWR_Fieldset", parentId: "wf-01-twr" },
    { id: "wf-02", name: "Electrical & Collection", code: "WF-02", fieldset: "WF_PWR_Fieldset", hasSubtypes: true },
    { id: "wf-02-conv", name: "Power Conversion", code: "WF-02-CONV", fieldset: "WF_PWR_Fieldset", parentId: "wf-02", hasSubtypes: true },
    { id: "wf-02-conv-ful", name: "Full Converter Assembly", code: "WF-02-CONV-FUL", fieldset: "WF_PWR_Fieldset", parentId: "wf-02-conv" },
    { id: "wf-02-conv-lv", name: "LV Converter Modules", code: "WF-02-CONV-LV", fieldset: "WF_PWR_Fieldset", parentId: "wf-02-conv" },
    { id: "wf-02-col", name: "MV Collection", code: "WF-02-COL", fieldset: "WF_COL_Fieldset", parentId: "wf-02", hasSubtypes: true },
    { id: "wf-02-col-mv", name: "MV Cable Systems", code: "WF-02-COL-MV", fieldset: "WF_COL_Fieldset", parentId: "wf-02-col" },
    { id: "wf-02-col-ss", name: "Pad-Mount / String Substations", code: "WF-02-COL-SS", fieldset: "WF_COL_Fieldset", parentId: "wf-02-col" },
    { id: "wf-03", name: "Substation & Grid Interface", code: "WF-03", fieldset: "WF_SUB_Fieldset", hasSubtypes: true },
    { id: "wf-03-swg", name: "HV Switchgear", code: "WF-03-SWG", fieldset: "WF_SUB_Fieldset", parentId: "wf-03" },
    { id: "wf-03-poi", name: "Point of Interconnection", code: "WF-03-POI", fieldset: "WF_SUB_Fieldset", parentId: "wf-03" },
    { id: "wf-03-rtc", name: "Reactive Compensation", code: "WF-03-RTC", fieldset: "WF_SUB_Fieldset", parentId: "wf-03" },
    { id: "wf-04", name: "Balance of Plant", code: "WF-04", fieldset: "WF_BOP_Fieldset", hasSubtypes: true },
    { id: "wf-04-met", name: "Meteorological Towers", code: "WF-04-MET", fieldset: "WF_BOP_Fieldset", parentId: "wf-04" },
    { id: "wf-04-om", name: "O&M Facilities", code: "WF-04-OM", fieldset: "WF_BOP_Fieldset", parentId: "wf-04" },
    { id: "wf-04-sc", name: "SCADA & Telecommunications", code: "WF-04-SC", fieldset: "WF_BOP_Fieldset", parentId: "wf-04" },
    { id: "wf-05", name: "Site & Civil", code: "WF-05", fieldset: "WF_CIV_Fieldset", hasSubtypes: true },
    { id: "wf-05-rd", name: "Access Roads & Crane Pads", code: "WF-05-RD", fieldset: "WF_CIV_Fieldset", parentId: "wf-05" },
    { id: "wf-05-drn", name: "Drainage & Erosion Control", code: "WF-05-DRN", fieldset: "WF_CIV_Fieldset", parentId: "wf-05" },
  ],
  "template-highways": [
    { id: "hw-01", name: "Pavement & Surfacing", code: "HW-01", fieldset: "HW_PAV_Fieldset", hasSubtypes: true },
    { id: "hw-01-asp", name: "Asphalt Pavement", code: "HW-01-ASP", fieldset: "HW_PAV_Fieldset", parentId: "hw-01" },
    { id: "hw-01-con", name: "Concrete Pavement", code: "HW-01-CON", fieldset: "HW_PAV_Fieldset", parentId: "hw-01" },
    { id: "hw-02", name: "Bridges & Structures", code: "HW-02", fieldset: "HW_BRG_Fieldset", hasSubtypes: true },
    { id: "hw-02-dck", name: "Bridge Decks", code: "HW-02-DCK", fieldset: "HW_BRG_Fieldset", parentId: "hw-02" },
    { id: "hw-02-jnt", name: "Bearings & Expansion Joints", code: "HW-02-JNT", fieldset: "HW_BRG_Fieldset", parentId: "hw-02" },
    { id: "hw-03", name: "Drainage & Stormwater", code: "HW-03", fieldset: "HW_DR_Fieldset", hasSubtypes: true },
    { id: "hw-03-cul", name: "Culverts", code: "HW-03-CUL", fieldset: "HW_DR_Fieldset", parentId: "hw-03" },
    { id: "hw-03-int", name: "Storm Inlets & Conveyance", code: "HW-03-INT", fieldset: "HW_DR_Fieldset", parentId: "hw-03" },
    { id: "hw-04", name: "ITS & Traffic Systems", code: "HW-04", fieldset: "HW_ITS_Fieldset", hasSubtypes: true },
    { id: "hw-04-sig", name: "Traffic Signals", code: "HW-04-SIG", fieldset: "HW_ITS_Fieldset", parentId: "hw-04" },
    { id: "hw-04-vms", name: "Variable Message Signs", code: "HW-04-VMS", fieldset: "HW_ITS_Fieldset", parentId: "hw-04" },
    { id: "hw-04-cam", name: "CCTV & Vehicle Detection", code: "HW-04-CAM", fieldset: "HW_ITS_Fieldset", parentId: "hw-04" },
    { id: "hw-05", name: "Lighting & Electrical", code: "HW-05", fieldset: "HW_EL_Fieldset", hasSubtypes: true },
    { id: "hw-05-lgt", name: "Highway Lighting", code: "HW-05-LGT", fieldset: "HW_EL_Fieldset", parentId: "hw-05" },
    { id: "hw-05-pwr", name: "Electrical Service & Cabinets", code: "HW-05-PWR", fieldset: "HW_EL_Fieldset", parentId: "hw-05" },
    { id: "hw-06", name: "Safety & Barriers", code: "HW-06", fieldset: "HW_SA_Fieldset", hasSubtypes: true },
    { id: "hw-06-grd", name: "Guardrail & Cable Barrier", code: "HW-06-GRD", fieldset: "HW_SA_Fieldset", parentId: "hw-06" },
    { id: "hw-06-att", name: "Crash Cushions & End Treatments", code: "HW-06-ATT", fieldset: "HW_SA_Fieldset", parentId: "hw-06" },
  ],
  "template-airport": [
    { id: "ap-01", name: "Runways & Airfield Pavement", code: "AP-01", fieldset: "AP_PAV_Fieldset", hasSubtypes: true },
    { id: "ap-01-rwy", name: "Runway Pavement", code: "AP-01-RWY", fieldset: "AP_PAV_Fieldset", parentId: "ap-01" },
    { id: "ap-01-twy", name: "Taxiway & Apron Pavement", code: "AP-01-TWY", fieldset: "AP_PAV_Fieldset", parentId: "ap-01" },
    { id: "ap-02", name: "Airfield Lighting", code: "AP-02", fieldset: "AP_AFL_Fieldset", hasSubtypes: true },
    { id: "ap-02-als", name: "Approach & ALS Systems", code: "AP-02-ALS", fieldset: "AP_AFL_Fieldset", parentId: "ap-02" },
    { id: "ap-02-rel", name: "Runway Edge & Taxiway Lighting", code: "AP-02-REL", fieldset: "AP_AFL_Fieldset", parentId: "ap-02" },
    { id: "ap-03", name: "Baggage Handling", code: "AP-03", fieldset: "AP_BHS_Fieldset", hasSubtypes: true },
    { id: "ap-03-cnv", name: "BHS Conveyors & Transfers", code: "AP-03-CNV", fieldset: "AP_BHS_Fieldset", parentId: "ap-03" },
    { id: "ap-03-srt", name: "Sortation & Make-up", code: "AP-03-SRT", fieldset: "AP_BHS_Fieldset", parentId: "ap-03" },
    { id: "ap-04", name: "Terminal Building Systems", code: "AP-04", fieldset: "AP_TRM_Fieldset", hasSubtypes: true },
    { id: "ap-04-hva", name: "Terminal HVAC", code: "AP-04-HVA", fieldset: "AP_TRM_Fieldset", parentId: "ap-04" },
    { id: "ap-04-jbr", name: "Passenger Boarding Bridges", code: "AP-04-JBR", fieldset: "AP_TRM_Fieldset", parentId: "ap-04" },
    { id: "ap-05", name: "Ground Support & Fuel", code: "AP-05", fieldset: "AP_GSE_Fieldset", hasSubtypes: true },
    { id: "ap-05-fue", name: "Aircraft Fueling & Hydrants", code: "AP-05-FUE", fieldset: "AP_GSE_Fieldset", parentId: "ap-05" },
    { id: "ap-05-gpu", name: "Ground Power & PCA", code: "AP-05-GPU", fieldset: "AP_GSE_Fieldset", parentId: "ap-05" },
    { id: "ap-06", name: "Security & Perimeter", code: "AP-06", fieldset: "AP_SEC_Fieldset", hasSubtypes: true },
    { id: "ap-06-fen", name: "Perimeter Fencing & Gates", code: "AP-06-FEN", fieldset: "AP_SEC_Fieldset", parentId: "ap-06" },
    { id: "ap-06-acs", name: "Access Control & Badging", code: "AP-06-ACS", fieldset: "AP_SEC_Fieldset", parentId: "ap-06" },
  ],
} as unknown as Record<string, AssetType[]>
